//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektWPF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lokalizace {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lokalizace() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektWPF.Lokalizace", typeof(Lokalizace).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc Of the Room: .
        /// </summary>
        internal static string DescOftheRoom {
            get {
                return ResourceManager.GetString("DescOftheRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string HeaderInventory {
            get {
                return ResourceManager.GetString("HeaderInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string HeaderItems {
            get {
                return ResourceManager.GetString("HeaderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno lokace.
        /// </summary>
        internal static string HeaderLang {
            get {
                return ResourceManager.GetString("HeaderLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of the Room: .
        /// </summary>
        internal static string NameOftheRoom {
            get {
                return ResourceManager.GetString("NameOftheRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okolní Lokace.
        /// </summary>
        internal static string OkolniLokaceLang {
            get {
                return ResourceManager.GetString("OkolniLokaceLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okolní Místnosti.
        /// </summary>
        internal static string OkolniMistnostiLang {
            get {
                return ResourceManager.GetString("OkolniMistnostiLang", resourceCulture);
            }
        }
    }
}
